language: python

notifications:
  email: false

addons:
  apt:
    packages:
      # commented as ubuntu's sundials is too old
      #- libsundials-serial-dev
      - gfortran
      - liblapack-dev

sudo: false
dist: bionic

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/sundials

matrix:
  include:
    # needed to work around https://github.com/travis-ci/travis-ci/issues/4794
    - python: 3.7
      env:
      - TOXENV=py37 SUNDIALS_VERSION='5.7.0'
    - python: 3.8
      env:
      - TOXENV=py38 SUNDIALS_VERSION='5.7.0'
    - python: 3.9
      env:
      - TOXENV=py39 SUNDIALS_VERSION='5.7.0'
    - python: 3.7
      env:
      - TOXENV=docs SUNDIALS_VERSION='5.7.0'
    - python: 3.7
      env:
      - TOXENV=check-manifest SUNDIALS_VERSION='5.7.0'
    - python: 3.7
      env:
      - TOXENV=checkreadme SUNDIALS_VERSION='5.7.0'

    # Reduced Index Size - this allows use of lapack linsolvers - default is -64
    - python: 3.7
      env:
      - TOXENV=py37 SUNDIALS_VERSION='5.7.0' SUNDIALS_INDEX_SIZE='32'

    # Additional precisions - default is 'double'
    - python: 3.7
      env:
      - TOXENV=py37 SUNDIALS_VERSION='5.7.0' SUNDIALS_PRECISION='single'
    - python: 3.7
      env:
      - TOXENV=py37 SUNDIALS_VERSION='5.7.0' SUNDIALS_PRECISION='extended' SUNDIALS_INDEX_SIZE='64'
    - python: 3.7
      env:
      - TOXENV=py37 SUNDIALS_VERSION='5.7.0' SUNDIALS_PRECISION='extended' SUNDIALS_INDEX_SIZE='64'

  allow_failures:
    - python: 3.7
      env:
      - TOXENV=py37 SUNDIALS_VERSION='5.7.0' SUNDIALS_PRECISION='single'

install:
  - source ci_support/ensure_sundials_installed.sh
  - pip install -U pip virtualenv wheel
  - pip install "setuptools<=64.0.0"
  - pip install -U tox-travis

script:
  - tox --workdir $HOME
