language: python

notifications:
  email: false

dist: trusty

addons:
  apt:
    packages:
      # commented as ubuntu's sundials is too old
      #- libsundials-serial-dev
      - gfortran
      - liblapack-dev

sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/sundials

env:
  - TOXENV=check-manifest SUNDIALS_VERSION='2.7.0'
  - TOXENV=checkreadme SUNDIALS_VERSION='2.7.0'

matrix:
  include:
    - python: 2.7
      env:
      - TOXENV=py27 SUNDIALS_VERSION='2.7.0'
    - python: 3.3
      env:
      - TOXENV=py33 SUNDIALS_VERSION='2.7.0'
    - python: 3.4
      env:
      - TOXENV=py34 SUNDIALS_VERSION='2.7.0'
    - python: 3.5
      env:
      - TOXENV=py35 SUNDIALS_VERSION='2.7.0'
    - python: 3.6
      env:
      - TOXENV=py36 SUNDIALS_VERSION='2.7.0'

install:
  - source ci_support/ensure_sundials_installed.sh
  - pip install -U pip setuptools virtualenv wheel
  - pip install -U tox

script:
  - tox
